### ISSUE TITLE
The request of the corresponding paper of this project

### ISSUE THREAD

**Issue by xiaopengguo1406** [TommeyChang/segmentation#1]
Dear TommeyChange
I'm xiaopengguo, a postgraduate student from Yunnan University. I think this project is very enlightening for my current work. However, I did not understand the code completely. So, could you send me the corresponding paper of this project to the Email: xiaopengguo@mail.ynu.edu.cn?

Thanks lot!

xiaopengguo (郭晓鹏)
Yunnan University
Email：xiaopengguo@mail.ynu.edu.cn

**Comment by TommeyChang** [comment]
I am sorry to replay you so late. This work is just an idea, which I fail to make it into reality.
